name: Query Runners and Deploy

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Docker image tag to deploy'
        required: true
        type: string
      run_uuid:
        description: 'Optional run UUID'
        required: false
        type: string

env:
  AWS_REGION: us-east-1

jobs:
  check-runners:
    runs-on: ubuntu-latest
    permissions:
      contents: read       # to read centers.json
      actions: none        # we'll use our PAT for the REST call
    outputs:
      valid_centers:   ${{ steps.filter.outputs.valid_centers }}
      missing_centers: ${{ steps.filter.outputs.missing_centers }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Fetch repo‑level runners
        id: fetch
        run: |
          curl -s -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.ACTIONS_PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/devopgitcs/test_centers/actions/runners \
            > runners.json

      - name: Filter Available vs Missing Centers
        id: filter
        run: |
          # 1) turn your centers.json keys into a space-separated list
          CENTER_IDS=$(jq -r 'keys_unsorted | join(" ")' .github/data/centers.json)

          VALID=()
          MISSING=()

          for center in $CENTER_IDS; do
            # lookup the runner-label for this center
            label=$(jq -r --arg C "$center" '.[$C]' .github/data/centers.json)

            # does any runner have exactly that label?
            if jq -e --arg L "$label" '.runners[] | select(.labels[].name == $L)' runners.json > /dev/null; then
              VALID+=("$center")
            else
              MISSING+=("$center")
            fi
          done

          # helper: bash-array → compact JSON array
          to_json() {
            if [ $# -eq 0 ]; then
              echo '[]'
            else
              printf '%s\n' "$@" | jq -R . | jq -s .
            fi
          }

          # write outputs
          echo "valid_centers=$(to_json "${VALID[@]}")"   >> $GITHUB_OUTPUT
          echo "missing_centers=$(to_json "${MISSING[@]}")" >> $GITHUB_OUTPUT

      - name: Warn About Missing Centers
        if: ${{ steps.filter.outputs.missing_centers != '[]' }}
        run: |
          echo "⚠️  Skipping centers with no runner available:"
          echo "${{ steps.filter.outputs.missing_centers }}"

      - name: Fail If No Valid Centers
        if: ${{ steps.filter.outputs.valid_centers == '[]' }}
        run: |
          echo "❌  No valid centers found – exiting."
          exit 1

  deploy:
    needs: check-runners
    strategy:
      matrix:
        center: ${{ fromJson(needs.check-runners.outputs.valid_centers) }}
    runs-on: ${{ matrix.center }}

    steps:
      - name: Dispatch Docker Compose Deploy
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: docker_compose_deploy.yml
          token: ${{ secrets.ACTIONS_PAT }}
          inputs: |
            {
              "tag_name": "${{ inputs.tag_name }}",
              "run_uuid": "${{ inputs.run_uuid }}",
              "center_id": "${{ matrix.center }}"
            }
