name: Query Runners and Deploy

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: Docker image tag to deploy
        required: true
        type: string
      run_uuid:
        description: Optional run UUID
        required: false
        type: string

# We only need read access to code; we'll call the API with our PAT
permissions:
  contents: read
  actions: none

jobs:
  check-runners:
    runs-on: ubuntu-latest
    outputs:
      valid_centers:   ${{ steps.filter.outputs.valid_centers }}
      missing_centers: ${{ steps.filter.outputs.missing_centers }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Show centers.json
        run: |
          echo "=== centers.json ==="
          cat .github/data/centers.json
          echo

      - name: Fetch self‑hosted runners
        id: fetch
        run: |
          echo "Calling GitHub API for repo‑level runners…"
          curl -sSL \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.ACTIONS_PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/devopgitcs/test_centers/actions/runners \
          > runners.json
          echo "=== runners.json ==="
          cat runners.json
          echo

      - name: Filter valid vs missing centers
        id: filter
        run: |
          VALID=()
          MISSING=()

          # iterate each center_id (the keys in centers.json)
          for center in $(jq -r 'keys_unsorted[]' .github/data/centers.json); do
            label=$(jq -r --arg c "$center" '.[$c]' .github/data/centers.json)
            echo "Center: $center  →  looking for runner-label: $label"

            # check if any runner has that label
            if jq -e --arg L "$label" '.runners[] | select(.labels[].name == $L)' runners.json > /dev/null; then
              echo "  ✔ runner-label '$label' exists"
              VALID+=("$center")
            else
              echo "  ✘ runner-label '$label' not found"
              MISSING+=("$center")
            fi
          done

          echo
          echo "Valid centers:   ${VALID[*]:-<none>}"
          echo "Missing centers: ${MISSING[*]:-<none>}"
          echo

          # helper to turn a bash-array into a JSON array
          to_json() {
            [ $# -eq 0 ] && { echo '[]'; return; }
            printf '%s\n' "$@" | jq -R . | jq -s .
          }

          echo "valid_centers=$(to_json "${VALID[@]}")"    >> $GITHUB_OUTPUT
          echo "missing_centers=$(to_json "${MISSING[@]}")" >> $GITHUB_OUTPUT

      - name: Warn about missing
        if: ${{ steps.filter.outputs.missing_centers != '[]' }}
        run: |
          echo "WARNING: skipping centers: ${{ steps.filter.outputs.missing_centers }}"

      - name: Fail if no centers left
        if: ${{ steps.filter.outputs.valid_centers == '[]' }}
        run: |
          echo "ERROR: no valid centers found – exiting."
          exit 1

  dispatch-deploy:
    name: Dispatch Docker Compose Deploy
    needs: check-runners
    runs-on: ubuntu-latest
    strategy:
      matrix:
        center: ${{ fromJson(needs.check-runners.outputs.valid_centers) }}

    steps:
      - name: Dispatch per‑center deploy
        uses: benc-uk/workflow-dispatch@v1
        with:
          token: ${{ secrets.ACTIONS_PAT }}
          workflow: docker_compose_deploy.yml
          ref: main
          inputs: |
            {
              "tag_name": "${{ inputs.tag_name }}",
              "run_uuid": "${{ inputs.run_uuid }}",
              "center_id": "${{ matrix.center }}"
            }
