# .github/workflows/deploy_to_centers.yml
name: Query Runners and Deploy

on:
  workflow_dispatch:
    inputs:
      tag_name:
        required: true
        type: string
      run_uuid:
        required: false
        type: string

env:
  AWS_REGION: us-east-1

jobs:
  check-runners:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: none
    outputs:
      valid_labels: ${{ steps.filter.outputs.valid_labels }}
      offline_labels: ${{ steps.filter.outputs.offline_labels }}
      missing_labels: ${{ steps.filter.outputs.missing_labels }}

    steps:
      - uses: actions/checkout@v4

      - name: Fetch org‑level runners
        id: fetch
        run: |
          curl -s \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.ACTIONS_PAT }}" \
            https://api.github.com/orgs/devopgitcs/actions/runners \
            > runners.json

      - name: Filter by runner‑labels
        id: filter
        run: |
          mapping=$(jq -c '.' .github/data/centers.json)
          offline=$(jq -r '.runners[] | select(.status=="offline") | .name' runners.json)

          valid=(); off=(); missing=()
          for label in $(echo "$mapping" | jq -r '.[]'); do
            runner=$(jq -r --arg L "$label" \
              '.runners[] | select(.labels[].name == $L) | .name' runners.json)

            if [ -z "$runner" ]; then
              missing+=("$label")
            elif echo "$offline" | grep -qx "$runner"; then
              off+=("$label")
            else
              valid+=("$label")
            fi
          done

          to_json() {
            if [ $# -eq 0 ]; then
              echo '[]'
            else
              printf '%s\n' "$@" | jq -R . | jq -s -c .
            fi
          }

          echo "valid_labels=$(to_json "${valid[@]}")" >> $GITHUB_OUTPUT
          echo "offline_labels=$(to_json "${off[@]}")" >> $GITHUB_OUTPUT
          echo "missing_labels=$(to_json "${missing[@]}")" >> $GITHUB_OUTPUT

      - name: Warn & fail if needed
        run: |
          echo "⚠️ Offline: ${{ steps.filter.outputs.offline_labels }}"
          echo "⚠️ Missing: ${{ steps.filter.outputs.missing_labels }}"
          if [ "$(echo '${{ steps.filter.outputs.valid_labels }}' | jq length)" -eq 0 ]; then
            exit 1
          fi

  deploy:
    needs: check-runners
    strategy:
      matrix:
        label: ${{ fromJson(needs.check-runners.outputs.valid_labels) }}
    runs-on:
      - self-hosted
      - ${{ matrix.label }}

    steps:
      - uses: actions/checkout@v4

      - name: Render docker‑compose.yml
        run: |
          sed -e "s|\${IMAGE_TAG}|${{ inputs.tag_name }}|" \
              -e "s|\${REPLACE_CENTER_ID}|${{ matrix.label }}|" \
              docker-compose.yml.template > docker-compose.yml

      - name: Run Docker Compose
        run: |
          docker-compose up --build -d
          docker-compose ps
