# .github/workflows/deploy_to_centers.yml
name: Query Runners and Deploy

on:
  workflow_dispatch:
    inputs:
      tag_name:
        required: true
        type: string
      run_uuid:
        required: false
        type: string

env:
  AWS_REGION: us-east-1

jobs:
  check-runners:
    runs-on: ubuntu-latest
    permissions:
      contents: read         # to read centers.json
      actions: none          # we’re using a PAT instead
    outputs:
      valid_centers: ${{ steps.filter-runners.outputs.valid_centers }}
      offline_centers: ${{ steps.filter-runners.outputs.offline_centers }}
      no_label_centers: ${{ steps.filter-runners.outputs.no_label_centers }}

    steps:
      # 1) Checkout the repo so we can read .github/data/centers.json
      - name: Checkout code
        uses: actions/checkout@v4

      # 2) Fetch org‑level runners via your PAT
      - name: Fetch runners (raw)
        id: fetch-raw
        run: |
          curl -s -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.ACTIONS_PAT }}" \
            https://api.github.com/orgs/devopgitcs/actions/runners \
            > runners.raw.json
          echo "=== RAW RESPONSE ==="
          cat runners.raw.json
          echo "=== end RAW ==="

      # 3) Parse that into an array file
      - name: Parse runners JSON
        id: fetch-runners
        run: |
          jq -c '.runners[]' runners.raw.json > runners.json
          echo "Parsed $(wc -l < runners.json) runners"

      # 4) Filter into valid / offline / no‑label
      - name: Filter centers
        id: filter-runners
        run: |
          # read mapping into a shell variable
          mapping=$(jq -c '.' .github/data/centers.json)

          # collect runner names that are offline
          offline_names=$(jq -r 'select(.status=="offline")|.name' runners.json)

          valid=(); off=(); no_label=()

          for center in $(echo "$mapping" | jq -r 'keys[]'); do
            label=$(echo "$mapping" | jq -r --arg c "$center" '.[$c]')
            # find any runner with that label
            match=$(jq -r --arg L "$label" '.[]|select(.labels|index($L))|.name' runners.json)

            if [ -z "$match" ]; then
              no_label+=("$center")
            elif echo "$offline_names" | grep -qx "$match"; then
              off+=("$center")
            else
              valid+=("$center")
            fi
          done

          # helper to turn a bash array into JSON
          to_json(){ printf '%s\n' "$@" | jq -R . | jq -s .; }

          echo "::set-output name=valid_centers::$(to_json "${valid[@]}")"
          echo "::set-output name=offline_centers::$(to_json "${off[@]}")"
          echo "::set-output name=no_label_centers::$(to_json "${no_label[@]}")"

      # 5) Warn and fail if no valid centers
      - name: Warn or fail
        run: |
          echo "⚠️ Offline centers: ${{ steps.filter-runners.outputs.offline_centers }}"
          echo "⚠️ No‑label centers: ${{ steps.filter-runners.outputs.no_label_centers }}"
          if [ "$(echo '${{ steps.filter-runners.outputs.valid_centers }}' | jq length)" -eq 0 ]; then
            echo "❌ No valid centers – exiting."
            exit 1
          fi

  deploy:
    needs: check-runners
    strategy:
      matrix:
        center: ${{ fromJson(needs.check-runners.outputs.valid_centers) }}
    runs-on: ${{ matrix.center }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Render docker-compose.yml
        run: |
          sed -e "s|\${IMAGE_TAG}|${{ inputs.tag_name }}|" \
              -e "s|\${REPLACE_CENTER_ID}|${{ matrix.center }}|" \
              docker-compose.yml.template > docker-compose.yml
          cat docker-compose.yml

      - name: Run Docker Compose
        run: |
          docker-compose up --build -d
          docker-compose ps
