# .github/workflows/deploy_to_centers.yml
name: Query Runners and Deploy

on:
  workflow_dispatch:
    inputs:
      tag_name:
        required: true
        type: string
      run_uuid:
        required: false
        type: string

jobs:
  check-runners:
    runs-on: ubuntu-latest
    permissions:
      contents: read      # to read centers.json
      actions: none       # we call the Actions API with our PAT
    outputs:
      valid_centers:   ${{ steps.filter.outputs.valid_centers }}
      missing_centers: ${{ steps.filter.outputs.missing_centers }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Show centers.json
        run: |
          echo "=== centers.json ==="
          cat .github/data/centers.json
          echo

      - name: Fetch organization runners
        id: fetch
        run: |
          echo "=== runners.json ==="
          curl -s -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.ACTIONS_PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/orgs/devopgitcs/actions/runners \
            > runners.json
          cat runners.json
          echo

      - name: Filter available vs. missing centers
        id: filter
        run: |
          # build a list of the center IDs (the keys of centers.json)
          CENTER_IDS=$(jq -r 'keys_unsorted[]' .github/data/centers.json)

          VALID=()
          MISSING=()

          for center in $CENTER_IDS; do
            label=$(jq -r --arg C "$center" '.[$C]' .github/data/centers.json)
            echo "Center '$center' expects runner label '$label'"

            if jq -e --arg L "$label" '.runners[] | select(.labels[].name == $L)' runners.json > /dev/null; then
              echo "  Found runner with label '$label'"
              VALID+=("$center")
            else
              echo "  No runner with label '$label'"
              MISSING+=("$center")
            fi
          done

          # helper: bash array → compact JSON
          to_json() {
            if [ $# -eq 0 ]; then
              echo "[]"
            else
              printf '%s\n' "$@" | jq -R . | jq -s -c .
            fi
          }

          # write outputs
          echo "valid_centers=$(to_json "${VALID[@]}")"   >> $GITHUB_OUTPUT
          echo "missing_centers=$(to_json "${MISSING[@]}")" >> $GITHUB_OUTPUT

      - name: Warn about missing centers
        if: ${{ steps.filter.outputs.missing_centers != '[]' }}
        run: |
          echo "Skipping centers (no matching runner): ${{ steps.filter.outputs.missing_centers }}"

      - name: Fail if no centers available
        if: ${{ steps.filter.outputs.valid_centers == '[]' }}
        run: |
          echo "No valid centers found – exiting."
          exit 1

  deploy:
    needs: check-runners
    strategy:
      matrix:
        center: ${{ fromJson(needs.check-runners.outputs.valid_centers) }}
    runs-on: ${{ matrix.center }}

    steps:
      - name: Dispatch Docker Compose Deploy
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: docker_compose_deploy.yml
          token: ${{ secrets.ACTIONS_PAT }}
          inputs: |
            {
              "tag_name": "${{ inputs.tag_name }}",
              "run_uuid": "${{ inputs.run_uuid }}",
              "center_id": "${{ matrix.center }}"
            }
