# .github/workflows/docker_compose_deploy.yml
name: Docker Compose Deploy

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: Docker image tag to deploy
        required: true
        type: string
      run_uuid:
        description: Optional run UUID for tracking
        required: false
        type: string
      center_id:
        description: Runner label (center) to use
        required: true
        type: string

permissions:
  contents: read

jobs:
  deploy:
    runs-on: [ self-hosted, ${{ inputs.center_id }} ]
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "Deploying center: ${{ inputs.center_id }}"
          echo "Image tag:        ${{ inputs.tag_name }}"
          [ -n "${{ inputs.run_uuid }}" ] && echo "Run UUID:      ${{ inputs.run_uuid }}"
      - run: |
          export IMAGE_TAG=${{ inputs.tag_name }}
          export CENTER_ID=${{ inputs.center_id }}
          docker-compose pull
          docker-compose up -d --build
      - run: docker-compose ps
