# .github/workflows/docker_compose_deploy.yml
name: Docker Compose Deploy

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: Docker image tag to deploy
        required: true
        type: string
      run_uuid:
        description: Optional run UUID
        required: false
        type: string
      center_id:
        description: Runner label (center) to use
        required: true
        type: string

permissions:
  contents: read    # to checkout code

jobs:
  deploy:
    runs-on: [ self-hosted, ${{ inputs.center_id }} ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log info
        run: |
          echo "Deploying center: ${{ inputs.center_id }}"
          echo "Image tag:        ${{ inputs.tag_name }}"
          [ -n "${{ inputs.run_uuid }}" ] && echo "Run UUID:    ${{ inputs.run_uuid }}"

      - name: Run Docker Compose
        run: |
          export IMAGE_TAG=${{ inputs.tag_name }}
          export CENTER_ID=${{ inputs.center_id }}
          docker-compose pull
          docker-compose up -d --build

      - name: Verify
        run: docker-compose ps
