name: Docker Compose Deploy

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: Docker image tag to deploy
        required: true
        type: string
      run_uuid:
        description: Optional run UUID for tracking
        required: false
        type: string
      center_id:
        description: Self‑hosted runner label (center) to use
        required: true
        type: string

permissions:
  contents: read

jobs:
  deploy:
    runs-on:
      - self-hosted
      - ${{ inputs.center_id }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log deployment info
        run: |
          echo "Deploying center: ${{ inputs.center_id }}"
          echo "Using image tag:   ${{ inputs.tag_name }}"
          if [ -n "${{ inputs.run_uuid }}" ]; then
            echo "Run UUID:         ${{ inputs.run_uuid }}"
          fi

      - name: Run Docker Compose
        run: |
          export IMAGE_TAG=${{ inputs.tag_name }}
          export CENTER_ID=${{ inputs.center_id }}
          docker-compose pull
          docker-compose up -d --build

      - name: Verify services
        run: docker-compose ps
